---
- name: Install Docker
  hosts: docker
  become: true
  #become_user: 
  become_method: sudo
  vars_files:
    - /etc/ansible/vaults/sudo.yml
  vars:
    container_count: 1
    portainer_name: portainer
    portainer_image: portainer/portainer-ce:latest
    portainer_agent_name: portainer-agent
    portainer_agent_image: portainer/agent:latest

  tasks:
    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install docker-ce
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        state: latest
        update_cache: yes

    #- name: Install Docker Module for Python
    #  pip:
    #    name: docker

    - name: Pull Portainer image
      community.docker.docker_image:
        name: "{{ portainer_agent_image }}"
        source: pull
    
    - name: Pull Portainer Agent image
      community.docker.docker_image:
        name: "{{ portainer_image }}"
        source: pull
    
    - name: Creates docker directory
      ansible.builtin.file:
        path: /docker/config
        state: directory
        mode: 0755

    - name: Install Portainer
      community.docker.docker_container:
        name: "{{ portainer_name }}"
        image: "{{ portainer_image }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /docker/config/portainer:/data
        ports:
          - 9443:9443 
          - 8000:8000
        restart_policy: unless-stopped
        #command: "{{ default_container_command }}"
        state: started
      #with_sequence: count={{ container_count }}

    - name: Install Portainer Agent
      community.docker.docker_container:
        name: "{{ portainer_agent_name }}"
        image: "{{ portainer_agent_image }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
          - 9001:9001
        restart_policy: unless-stopped
        #command: "{{ default_container_command }}"
        state: started
      #with_sequence: count={{ container_count }}
